spring.application.name=SimpleOnlineStore
spring.datasource.url=jdbc:mysql://localhost:3306/online_store
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

security.jwt.secret-key=3ERqvmEcA5QkbtSuPh1XelOtAgEUd0dMzS7uuMzAR8j
security.jwt.expiration-time=36000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hindochahitarth@gmail.com
spring.mail.password=ojyk abvm shno fdpj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key_id=rzp_test_TX1TB9ZVFwvYtg
razorpay.key_secret=l0sZXBCdjVGL5UYMw1HRvQq6

file.upload-dir=/home/hitarth/Documents

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hindochahitarth@gmail.com
spring.mail.password=ojyk abvm shno fdpj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razorpay.key_id=rzp_test_TX1TB9ZVFwvYtg
razorpay.key_secret=l0sZXBCdjVGL5UYMw1HRvQq6

file.upload-dir=/home/hitarth/Documents

